version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.2-stretch-browsers
        steps:
            - checkout
            - run: pip install --user -r requirements.txt
    deploy:
        docker:
            - image: buildpack-deps:trusty
        steps:
            - checkout
            - run:
                name: Deploy Master to Heroku
                command: |
                    git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

